# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('TalentProfile', '0001_initial'),
        ('Dancers', '0001_initial'),
        ('ChildArtist', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='TalentProfile_Actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Actors'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='TalentProfile_Child_Artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChildArtist.ChildArtist'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='TalentProfile_Dancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dancers.Dancer'),
        ),
    ]
