# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mimicry_artist', '0001_initial'),
        ('TalentProfile', '0002_auto_20180405_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='TalentProfile_Mimicry_Artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimicry_artist.MimicryArtist'),
        ),
    ]
