# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TalentProfile', '0004_talentprofile_talentprofile_model'),
        ('SpecialArt', '0001_initial'),
        ('Singer', '0001_initial'),
        ('musician', '0001_initial'),
        ('VoiceOverArtist', '0001_initial'),
        ('Theater_Actor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='TalentProfile_Musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.Musician'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='TalentProfile_Singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Singer.Singer'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='TalentProfile_Special_Art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpecialArt.SpecialArt'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='TalentProfile_Theater_Artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theater_Actor.theater_actor'),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='TalentProfile_Voice_Over_Artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoiceOverArtist.VoiceOverArtist'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_TalentProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsTalentProfile', to='TalentProfile.TalentProfile'),
        ),
    ]
