# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Costumes', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserCoinBox_Comment', models.CharField(max_length=150)),
                ('UserCoinBox_Comment_Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoinBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserCoinBox_Costume_ListUserCoinBox_Costume_List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costumes.Costume')),
                ('UserCoinBox_Location_List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Location')),
            ],
        ),
    ]
