# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actionvehicle', '0001_initial'),
        ('pets', '0001_initial'),
        ('UserCoinBox', '0001_initial'),
        ('Prop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinbox',
            name='UserCoinBox_Pet_List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pets'),
        ),
        migrations.AddField(
            model_name='usercoinbox',
            name='UserCoinBox_Prop_List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prop.Prop'),
        ),
        migrations.AddField(
            model_name='usercoinbox',
            name='UserCoinBox_Vehicle_List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actionvehicle.ActionVehicle'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_UserCoinBox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsUserCoinBox', to='UserCoinBox.UserCoinBox'),
        ),
    ]
