# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfileProjects', '0001_initial'),
        ('Location_Amenitie', '0001_initial'),
        ('image', '0001_initial'),
        ('Location_Category', '0001_initial'),
        ('video', '0001_initial'),
        ('Comments', '0002_auto_20180405_1018'),
        ('Ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Location_Authorities_Involved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locationss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='Location_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='Location_Category.Location_Category'),
        ),
        migrations.AddField(
            model_name='location',
            name='Location_Comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='Comments.Comments'),
        ),
        migrations.AddField(
            model_name='location',
            name='Location_Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crlocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='Location_Images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='image.Image'),
        ),
        migrations.AddField(
            model_name='location',
            name='Location_Profile_Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='ProfileProjects.ProfileProjects'),
        ),
        migrations.AddField(
            model_name='location',
            name='Location_Rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='Ratings.Rating'),
        ),
        migrations.AddField(
            model_name='location',
            name='Location_Shooting_Amminities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='Location_Amenitie.Location_Amenitie'),
        ),
        migrations.AddField(
            model_name='location',
            name='Location_Video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='video.video'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Location'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Location_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentlocation', to=settings.AUTH_USER_MODEL),
        ),
    ]
