# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecialArt_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecialArt_Charges_Available', models.BooleanField(max_length=200)),
                ('SpecialArt_Daily_Charges', models.IntegerField()),
                ('SpecialArt_Description', models.CharField(max_length=500)),
                ('SpecialArt_Special_Art_ID', models.CharField(max_length=200)),
                ('SpecialArt_Comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.Comments')),
            ],
        ),
    ]
