# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfileProjects', '0001_initial'),
        ('portfolio_element', '0001_initial'),
        ('SpecialArt', '0001_initial'),
        ('Ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialart',
            name='SpecialArt_Portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_element.PortfolioElement'),
        ),
        migrations.AddField(
            model_name='specialart',
            name='SpecialArt_Profile_Projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileProjects.ProfileProjects'),
        ),
        migrations.AddField(
            model_name='specialart',
            name='SpecialArt_Ratings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ratings.Rating'),
        ),
    ]
