# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfileProjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileprojects',
            name='ProfileProjects_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileProjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_ProfileProjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileProjects_Comment', to='ProfileProjects.ProfileProjects'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ProfileProjects_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileProjects_Commentss', to=settings.AUTH_USER_MODEL),
        ),
    ]
