# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Help_Qna_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HelpQna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Help_Qna_Answer', models.CharField(max_length=100)),
                ('Help_Qna_Article_Id', models.IntegerField()),
                ('Help_Qna_Question', models.CharField(max_length=100)),
                ('Help_Qna_Modified_Date', models.DateField(auto_now_add=True)),
                ('Help_Qna_Created_Date', models.DateField(auto_now_add=True)),
                ('Hel_Qna_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpqnas', to='Comments.Comments')),
            ],
        ),
    ]
