# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmLocationScheduleForPermit_Comment', models.CharField(max_length=150)),
                ('FilmLocationScheduleForPermit_Comment_Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilmLocationScheduleForPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmLocationScheduleForPermit_Location', models.CharField(max_length=100)),
                ('FilmLocationScheduleForPermit_ProjectID', models.CharField(max_length=100)),
                ('FilmLocationScheduleForPermit_SNo', models.CharField(max_length=100)),
                ('FilmLocationScheduleForPermit_Modified_Date', models.DateField(auto_now_add=True)),
                ('FilmLocationScheduleForPermit_Created_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
