# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FilmLocationScheduleForPermit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmlocationscheduleforpermit',
            name='FilmLocationScheduleForPermit_Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmlocationscheduleforpermits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_FilmLocationScheduleForPermit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsFilmLocationScheduleForPermit', to='FilmLocationScheduleForPermit.FilmLocationScheduleForPermit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='FilmLocationScheduleForPermit_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssFilmLocationScheduleForPermit', to=settings.AUTH_USER_MODEL),
        ),
    ]
