# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='Conversations_Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationss2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversations',
            name='Conversations_Message_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationss', to='message.Messages'),
        ),
        migrations.AddField(
            model_name='conversations',
            name='Conversations_Recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Conversations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_conversations', to='conversations.Conversations'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Conversations_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
