# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0002_auto_20180405_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='Pets_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pets',
            name='Pets_Images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pets', to='image.Image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pets_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pets'),
        ),
    ]
