# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoiceOverArtist_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceOverArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoiceOverArtist_Charges_Available', models.BooleanField()),
                ('VoiceOverArtist_Daily_charges', models.IntegerField(default=0)),
                ('VoiceOverArtist_Description', models.CharField(max_length=200)),
                ('VoiceOverArtist_Language', models.CharField(max_length=200)),
                ('VoiceOverArtist_Voice_Scale', models.CharField(max_length=200)),
                ('VoiceOverArtist_Created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
