# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Amenity_Adresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Amenity_Adresses_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_adresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Amenity_Adresses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_adress', to='Amenity_Adresses.Amenity_Adresses'),
        ),
        migrations.AddField(
            model_name='amenity_adresses',
            name='Amenity_Adresses_Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_adressess', to=settings.AUTH_USER_MODEL),
        ),
    ]
