# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dancer_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dancer_Charges_Available', models.BooleanField()),
                ('Dancer_Daily_Charges', models.CharField(max_length=100)),
                ('Dancer_Dancing_Style', models.CharField(max_length=100)),
                ('Dancer_Description', models.CharField(max_length=100)),
                ('Dancer_Genre', models.CharField(max_length=100)),
                ('Dancer_Modified_Date', models.DateField(auto_now_add=True)),
                ('Dancer_Created_Date', models.DateField(auto_now_add=True)),
                ('Dancer_Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancers', to='Comments.Comments')),
            ],
        ),
    ]
