# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfileProjects', '0001_initial'),
        ('portfolio_element', '0001_initial'),
        ('Dancers', '0001_initial'),
        ('video', '0001_initial'),
        ('Ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dancer',
            name='Dancer_Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dancer',
            name='Dancer_Portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancers', to='portfolio_element.PortfolioElement'),
        ),
        migrations.AddField(
            model_name='dancer',
            name='Dancer_Profile_Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancers', to='ProfileProjects.ProfileProjects'),
        ),
        migrations.AddField(
            model_name='dancer',
            name='Dancer_Rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancers', to='Ratings.Rating'),
        ),
        migrations.AddField(
            model_name='dancer',
            name='Dancer_Video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancers', to='video.video'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Dancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsDancer', to='Dancers.Dancer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Dancer_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssDancer', to=settings.AUTH_USER_MODEL),
        ),
    ]
