# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmLocationFromGuidedWithSerial_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FilmLocationFromGuidedWithSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmLocationFromGuidedWithSerial_Arrival_Time', models.DateField()),
                ('FilmLocationFromGuidedWithSerial_Departure_Time', models.CharField(max_length=100)),
                ('FilmLocationFromGuidedWithSerial_Location_From_Guideno', models.CharField(max_length=100)),
                ('FilmLocationFromGuidedWithSerial_Location', models.CharField(max_length=100)),
                ('FilmLocationFromGuidedWithSerial_Modified_Date', models.DateField(auto_now_add=True)),
                ('FilmLocationFromGuidedWithSerial_Created_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
