# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location_Authorities', '0002_locationauthority_location_authoritie_contact_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_query_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PermitQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PermitQuery_API_Address', models.CharField(max_length=200)),
                ('PermitQuery_City_State_Country', models.CharField(max_length=200)),
                ('PermitQuery_Latitude', models.IntegerField(default=0)),
                ('PermitQuery_List_Long_name', models.CharField(max_length=100)),
                ('PermitQuery_List_Short_Name', models.CharField(max_length=100)),
                ('PermitQuery_List_Type', models.CharField(max_length=100)),
                ('PermitQuery_Location', models.CharField(max_length=200)),
                ('PermitQuery_Longitude', models.IntegerField(default=0)),
                ('PermitQuery_Map_Address', models.CharField(max_length=100)),
                ('Permit_Query_Number', models.IntegerField(default=0)),
                ('PermitQuery_Query_Mode', models.CharField(max_length=200)),
                ('PermitQuery_Street_Address', models.CharField(max_length=200)),
                ('PermitQuery_Message', models.CharField(max_length=280)),
                ('PermitQuery_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('PermitQuery_Address_Components', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location_Authorities.LocationAuthority')),
            ],
        ),
    ]
