# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Comments_Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentss2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='Comments_Creatorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentss1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_Comment', to='Comments.Comments'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comments_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
