# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Code', models.CharField(max_length=100)),
                ('District_Complete', models.BooleanField()),
                ('District_Contact_Number', models.CharField(max_length=100)),
                ('District_Name', models.CharField(max_length=100)),
                ('District_Email', models.CharField(max_length=100)),
                ('District_Headquater', models.CharField(max_length=100)),
                ('District_Phq', models.CharField(max_length=100)),
                ('District_Phq_Email', models.CharField(max_length=100)),
                ('District_Phq_Postal_Address', models.CharField(max_length=100)),
                ('District_Phq_Web', models.CharField(max_length=100)),
                ('District_Police_Hqaddress', models.CharField(max_length=100)),
                ('District_Postal_Address', models.CharField(max_length=100)),
                ('District_State', models.CharField(max_length=100)),
                ('District_Web_Address', models.CharField(max_length=100)),
                ('District_Modified_Date', models.DateField(auto_now_add=True)),
                ('District_Created_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
