# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('actionvehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ActionVehicle_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionvehicle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Action_Vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='actionvehicle.ActionVehicle'),
        ),
        migrations.AddField(
            model_name='actionvehicle',
            name='ActionVehicle_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionvechicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionvehicle',
            name='ActionVehicle_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionvechiles1', to='image.Image'),
        ),
        migrations.AddField(
            model_name='actionvehicle',
            name='ActionVehicle_ownership_proof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionvechicles2', to='image.Image'),
        ),
    ]
