# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceCatagory_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceCatagory_Icon_Number', models.IntegerField()),
                ('ServiceCatagory_Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ServiceCatagory_Responsibilities', models.CharField(max_length=200)),
                ('ServiceCatagory_Service_Category', models.CharField(max_length=200)),
                ('ServiceCatagory_What_Do_You_Do', models.CharField(max_length=200)),
            ],
        ),
    ]
