# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ServiceCatagory', '0001_initial'),
        ('ServiceSubcatagory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatagory',
            name='ServiceCatagory_Service_Subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceSubcatagory.ServiceSubcatagory'),
        ),
    ]
