# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServiceCatagory', '0002_servicecatagory_servicecatagory_service_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatagory',
            name='ServiceCatagory_Users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_ServiceCatagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsServiceCatagory', to='ServiceCatagory.ServiceCatagory'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ServiceCatagory_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssServiceCatagory', to=settings.AUTH_USER_MODEL),
        ),
    ]
