# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Booking_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_Bookingnew', to='Booking.Booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
