# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubscriptionPlan_Comment', models.CharField(max_length=150)),
                ('SubscriptionPlan_Comment_Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubscriptionPlan_Amount', models.IntegerField()),
                ('SubscriptionPlan_End_Date', models.DateField()),
                ('SubscriptionPlan_FOR_FILM_COIN', models.IntegerField()),
                ('SubscriptionPlan_Location_Allowed', models.BooleanField()),
                ('SubscriptionPlan_Openings_Allowed', models.BooleanField()),
                ('SubscriptionPlan_Pitch_Allowed', models.BooleanField()),
                ('SubscriptionPlan_Pitch_Box_Capacity_Image_per_pitch', models.IntegerField()),
                ('SubscriptionPlan_Start_Date', models.DateField(auto_now_add=True)),
                ('SubscriptionPlan_Type', models.CharField(max_length=200)),
            ],
        ),
    ]
