# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SubscriptionPlan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='SubscriptionPlan_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_SubscriptionPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsSubscriptionPlan', to='SubscriptionPlan.SubscriptionPlan'),
        ),
        migrations.AddField(
            model_name='comment',
            name='SubscriptionPlan_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssSubscriptionPlan', to=settings.AUTH_USER_MODEL),
        ),
    ]
