# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_subcategory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quick_Requirements', '0001_initial'),
        ('location_pitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick_requirements',
            name='Quick_Requirements_Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Quick_Requirements_Creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quick_requirements',
            name='Quick_Requirements_From_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quick_requirements',
            name='Quick_Requirements_Pitch_List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quick_Requirements', to='location_pitch.LocationPitch'),
        ),
        migrations.AddField(
            model_name='quick_requirements',
            name='Quick_Requirements_Recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quick_requirements',
            name='Quick_Requirements_SUB_CATEGORY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quick_Requirements', to='location_subcategory.LocationSubCategory'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Quick_Requirements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentQuick_Requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Quick_Requirements_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AuthorQuick_Requirements', to='Quick_Requirements.Quick_Requirements'),
        ),
    ]
