# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmRecceRoute_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FilmRecceRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmRecceRoute_Distance', models.CharField(max_length=100)),
                ('FilmRecceRoute_Filmrecce_Name', models.CharField(max_length=100)),
                ('FilmRecceRoute_Route_Name', models.CharField(max_length=100)),
                ('FilmRecceRoute_Travel_Time', models.CharField(max_length=100)),
                ('FilmRecceRoute_Modified_Date', models.DateField(auto_now_add=True)),
                ('FilmRecceRoute_Created_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
