# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CircleInvite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='CircleInvite_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circleinvite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_CircleInvite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circleinvite_comments', to='CircleInvite.CircleInvite'),
        ),
        migrations.AddField(
            model_name='circleinvite',
            name='CircleInvite_Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circleinvites3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circleinvite',
            name='CircleInvite_From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circleinvites1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circleinvite',
            name='CircleInvite_To',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circleinvites2', to=settings.AUTH_USER_MODEL),
        ),
    ]
