# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ServiceCatagory', '0001_initial'),
        ('EducationInfos', '0001_initial'),
        ('ServiceSubcatagory', '0001_initial'),
        ('ProfileProjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserProfessionalInfo_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfessionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserProfessionalInfo_Account_Name', models.CharField(max_length=200, unique=True)),
                ('UserProfessionalInfo_Account_Number', models.IntegerField(default=-1)),
                ('UserProfessionalInfo_Bank_Name', models.CharField(max_length=200)),
                ('UserProfessionalInfo_Bank_Account', models.CharField(max_length=200)),
                ('UserProfessionalInfo_Charges_Negotiation', models.IntegerField(default=-1)),
                ('UserProfessionalInfo_Daily_Charges', models.IntegerField(default=-1)),
                ('UserProfessionalInfo_Expirienced', models.BooleanField(default=True)),
                ('UserProfessionalInfo_Hometown', models.FloatField(max_length=200)),
                ('UserProfessionalInfo_IFSI_CODE', models.CharField(max_length=200)),
                ('UserProfessionalInfo_Monthly_Charges', models.IntegerField(default=-1)),
                ('UserProfessionalInfo_Rates_Avialability', models.BooleanField(max_length=200)),
                ('Spoken_Languages', models.CharField(max_length=100)),
                ('Understandable_Knowledge', models.CharField(max_length=100)),
                ('UserProfessionalInfo_User_Proffessional_Category', models.CharField(max_length=200)),
                ('UserProfessionalInfo_Weekly_Charges', models.IntegerField(default=-1)),
                ('UserProfessionalInfo_Writtable_Language', models.CharField(max_length=200)),
                ('UserProfessionalInfo_Years_Of_Experience', models.IntegerField(default=-1)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCatagory.ServiceCatagory')),
                ('Designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceSubcatagory.ServiceSubcatagory')),
                ('Projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileProjects.ProfileProjects')),
                ('User_Education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationInfos.EducationInfo')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_UserProfessionalInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofessionalinfo_details', to='userprofessionalinfo.UserProfessionalInfo'),
        ),
    ]
