# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Costume_Comment', models.CharField(max_length=150)),
                ('Costume_Comment_Created_On', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Costume_Color', models.CharField(max_length=100)),
                ('Costume_Category', models.CharField(max_length=100)),
                ('Costume_Style', models.CharField(max_length=100)),
                ('Costume_Description', models.CharField(max_length=100)),
                ('Costume_Type', models.CharField(max_length=100)),
                ('Costume_Modification_Allowed', models.BooleanField()),
                ('Costume_Trend_Year', models.DateField()),
                ('Costume_Weekly_Rent', models.IntegerField()),
                ('Costume_Modified_Date', models.DateField(auto_now_add=True)),
                ('Costume_Created_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
