# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Costumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume',
            name='Costume_Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Costumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costume',
            name='Costume_Image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Costumes', to='image.Image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Costume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='Costumes.Costume'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Costume_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
