# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EducationInfos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinfo',
            name='EducationInfo_Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationInfos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_EducationInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsEducationInfo', to='EducationInfos.EducationInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='EducationInfo_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssEducationInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
