# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mimicry_artist', '0001_initial'),
        ('Ratings', '0002_auto_20180405_1018'),
        ('video', '0001_initial'),
        ('Comments', '0002_auto_20180405_1018'),
        ('portfolio_element', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProfileProjects', '0002_auto_20180405_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimicryartist',
            name='MimicryArtist_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mimicryartist',
            name='MimicryArtist_Comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MimicryArtist', to='Comments.Comments'),
        ),
        migrations.AddField(
            model_name='mimicryartist',
            name='MimicryArtist_Portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MimicryArtist', to='portfolio_element.PortfolioElement'),
        ),
        migrations.AddField(
            model_name='mimicryartist',
            name='MimicryArtist_Portfolio_Projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MimicryArtist', to='ProfileProjects.ProfileProjects'),
        ),
        migrations.AddField(
            model_name='mimicryartist',
            name='MimicryArtist_Rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MimicryArtist', to='Ratings.Rating'),
        ),
        migrations.AddField(
            model_name='mimicryartist',
            name='MimicryArtist_Video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MimicryArtist', to='video.video'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_mimicry_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimicry_artist.MimicryArtist'),
        ),
    ]
