# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_actor_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='theater_actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body_Type', models.CharField(max_length=200)),
                ('Daily_Charges', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=200)),
                ('Ethnicity', models.CharField(max_length=200)),
                ('Favorite_Acting_Style', models.CharField(max_length=200)),
                ('Financial_Available', models.BooleanField(default=False)),
                ('Height', models.IntegerField(default=0)),
                ('Language', models.CharField(max_length=100)),
                ('Skin_Color', models.CharField(max_length=200)),
                ('Special_Skills', models.CharField(max_length=200)),
                ('Theater_Actor_ID', models.IntegerField(default=0)),
                ('Weight', models.IntegerField(default=0)),
                ('theater_actor_Message', models.CharField(max_length=280)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.Comments')),
            ],
        ),
    ]
