# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Theater_Actor', '0001_initial'),
        ('portfolio_element', '0001_initial'),
        ('Ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater_actor',
            name='Portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_element.PortfolioElement'),
        ),
        migrations.AddField(
            model_name='theater_actor',
            name='Ratings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ratings.Rating'),
        ),
    ]
