# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Singer_Comment', models.CharField(max_length=150)),
                ('Singer_Comment_Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Singer_Daily_Charges', models.IntegerField()),
                ('Singer_Description', models.CharField(max_length=200)),
                ('Singer_Financials_Available', models.BooleanField(max_length=200)),
                ('Singer_Genre', models.CharField(max_length=200)),
                ('Singer_Languages', models.CharField(max_length=100)),
                ('Singer_Scale_Rate', models.CharField(max_length=200)),
                ('Singing_Style', models.CharField(max_length=100)),
                ('Singer_Comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.Comments')),
            ],
        ),
    ]
