# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_City', models.CharField(max_length=100)),
                ('Search_Key_Word', models.CharField(max_length=200)),
                ('Search_Range', models.IntegerField()),
                ('Search_Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Search_Modified_Date', models.DateTimeField(auto_now_add=True)),
                ('Search_CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comments.Comments')),
            ],
        ),
    ]
