# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location_Authorities', '0001_initial'),
        ('officer_contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationauthority',
            name='Location_Authoritie_Contact_Officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_authorities', to='officer_contact.OfficerContact'),
        ),
    ]
