# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Letter_pdf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='letter_pdf',
            name='Letter_pdf_Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letterpdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Letter_pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Letter_pdf.Letter_pdf'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Letter_pdf_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentletterpdf', to=settings.AUTH_USER_MODEL),
        ),
    ]
