# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmProjectForPermit_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FilmProjectForPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmProjectForPermit_Category', models.CharField(max_length=100)),
                ('FilmProjectForPermit_Crew_Size', models.CharField(max_length=100)),
                ('FilmProjectForPermit_Listoflocation_schedule', models.CharField(max_length=100)),
                ('FilmProjectForPermit_Project_Name', models.CharField(max_length=100)),
                ('FilmProjectForPermit_ScriptasFile', models.FileField(max_length=200, upload_to='file/')),
                ('FilmProjectForPermit_Synopsis', models.CharField(max_length=100)),
                ('FilmProjectForPermit_Title', models.CharField(max_length=100)),
                ('FilmProjectForPermit_Modified_Date', models.DateField(auto_now_add=True)),
                ('FilmProjectForPermit_Created_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
