# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FilmProjectForPermit', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmprojectforpermit',
            name='FilmProjectForPermit_Cast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmprojectforpermits_cast', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filmprojectforpermit',
            name='FilmProjectForPermit_Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FilmProjectForPermit_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filmprojectforpermit',
            name='FilmProjectForPermit_Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmprojectforpermits_Creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filmprojectforpermit',
            name='FilmProjectForPermit_PermitLocationList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmprojectforpermits', to='Location.Location'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_FilmProjectForPermit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsFilmProjectForPermit', to='FilmProjectForPermit.FilmProjectForPermit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='FilmProjectForPermit_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssFilmProjectForPermit', to=settings.AUTH_USER_MODEL),
        ),
    ]
