# Generated by Django 2.0.3 on 2018-04-05 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location_Category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Location', '0001_initial'),
        ('FilmRecceTourGuide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmreccetourguide',
            name='FilmRecceTourGuide_Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FilmRecceRoutesGuide', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filmreccetourguide',
            name='FilmRecceTourGuide_FilmLocationFromGuided',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FilmRecceTourGuide', to='Location_Category.Location_Category'),
        ),
        migrations.AddField(
            model_name='filmreccetourguide',
            name='FilmRecceTourGuide_guidedlocation_List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmreccetourguides', to='Location.Location'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_FilmRecceTourGuide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsFilmRecceTourGuide', to='FilmRecceTourGuide.FilmRecceTourGuide'),
        ),
        migrations.AddField(
            model_name='comment',
            name='FilmRecceTourGuide_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentssFilmRecceTourGuide', to=settings.AUTH_USER_MODEL),
        ),
    ]
